# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f65ea03f59f90542125cd9a02fff08c354b0dda034dbcf638264ffb04f6dfe68b4bf9f150e38e544f0695e4789c71164605a1ef3ff864c2692be848e88e7a4d0

test:
  secret_key_base: d85512c53fb9ddbe3269d8526525fe673c674978035e20f4cc411502185bba11c6948b0e042c35561f3eab80c96eb670ca874d58dcc0a8ef9f2a21598e54a33f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
